Wallet UX Issues
NethermindEth/starknet-remix-plugin pull request #264
Opened 2024-09-02 10:42 UTC by ashleendaly

- Wallet address now no longer has missing 0 when being copied and used in the faucet.
- Network now reflects the connected network in the browser plugin
- When a user copies a wallet address, a tick icon is displayed instead of the text "Copied". This keeps the UI cleaners and avoids overlapping text with the wallet address.

2024-09-02 11:12 UTC, satyambnsal commented on plugin/src/components/Wallet/index.tsx
> +import { correctWalletAddress, getChainName } from '../../utils/starknet'
minor: perhaps we change the method name to `formatWalletAddress` ?

2024-09-02 11:27 UTC, varex83 requested changes
- Can you also make this button in the manual account change to the checkmark?
![image](https://github.com/user-attachments/assets/a1ae7a62-1813-4e6e-9456-b2952a23b5e9)
- On my side, in "Remote Devnet" section button still shows "Copied", can we change it to the checkmark as well? 
![image](https://github.com/user-attachments/assets/5392977b-3e02-4b0f-af6c-3e0a6edd9bd1)
- Copy button in wallet connection works fine
- Also, please check the "Update" buttons, some of them doesn't rotate when triggered
- Plugin crashed after changing from "Wallet" connection to the "Manual Account" with following browser error (we can move out of this PR in the separate issue) 
![image](https://github.com/user-attachments/assets/c0fb64cc-4bbb-42ef-9c58-d49ebc4e143b)

2024-09-02 11:27 UTC, varex83 commented on plugin/src/utils/starknet.ts
> +  if (address === undefined) return ''
should we return "undefined" here as well?

2024-09-04 10:46 UTC, varex83 requested changes
GTG after fixing the typo

2024-09-04 10:46 UTC, varex83 commented on plugin/src/components/Wallet/index.tsx
> +import { foprmatWalletAddress, getChainName } from '../../utils/starknet'
I think you have a typo here :D

2024-09-04 17:13 UTC, merged